### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [pareshraut/Neural-Networks-for-Drum-Music-Generation#1]
Hi there, 1st of all thanks for your awesome work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO](https://github.com/forart/HyMPS#-) \ [AI-based projects page](https://github.com/forart/HyMPS/blob/main/AIaudio.md#--) \ [Drums subsection](https://github.com/forart/HyMPS/blob/main/AIaudio.md#drums-)), can you please add a "GH-compliant" license file ?

Expliciting licensing terms is extremely important to let other devs (and not only) understand how to reuse/adapt/modify your code in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/pareshraut/Neural-Networks-for-Drum-Music-Generation/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/pareshraut/Neural-Networks-for-Drum-Music-Generation/?label=LICENSE)

Anyway you can easily choose a "correct" one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - categorization/sorting of collected projects in order to push their evolution by favouring collaborations between developers (and not only).

Thanks in advance.

**Comment by pareshraut** [comment]
Hi Team, 
Thank you for creating such an amazing repository for devs. I have added a MIT license file to my repository, please let me know if there are any more changes I should make. I think categorization/sorting is pretty well done in the repository. I will note if I come across any bug.

**Comment by MarcoRavich** [comment]
Thanks a lot, as you can see above it works now.
